<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-L2JFHC2" name="com.cts.Academic.testcases.HomepageTest" tests="6" failures="1" timestamp="2020-04-06T15:30:50 IST" time="208.645" errors="0">
  <testcase name="vertify_homepage_title" time="26.584" classname="com.cts.Academic.testcases.HomepageTest"/>
  <system-out/>
  <testcase name="user_name_label_check" time="30.887" classname="com.cts.Academic.testcases.HomepageTest"/>
  <system-out/>
  <testcase name="verify_logo" time="32.497" classname="com.cts.Academic.testcases.HomepageTest"/>
  <system-out/>
  <testcase name="click_on_Arts_human_link" time="34.659" classname="com.cts.Academic.testcases.HomepageTest"/>
  <system-out/>
  <testcase name="click_on_medicine_health" time="44.393" classname="com.cts.Academic.testcases.HomepageTest">
    <failure type="java.lang.AssertionError" message="medicine&amp;health page not found expected [Medicine and health | Journals | Oxford Academic] but found [Journals | Oxford Academic]">
      <![CDATA[java.lang.AssertionError: medicine&health page not found expected [Medicine and health | Journals | Oxford Academic] but found [Journals | Oxford Academic]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at com.cts.Academic.testcases.HomepageTest.click_on_medicine_health(HomepageTest.java:88)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- click_on_medicine_health -->
  <system-out/>
  <testcase name="click_on_Acess_purchase_link" time="39.625" classname="com.cts.Academic.testcases.HomepageTest"/>
  <system-out/>
</testsuite> <!-- com.cts.Academic.testcases.HomepageTest -->
